name: ArcandiaNetwork
main: me.beefstew2007.arcandianetwork.Main
version: 1.0.0

commands:
    r-reload:
        description: Reload Ranks!
    rank:
        description: Rank players!
    gmc:
        description: gmc players!
    gms:
        description: gms players!